### ISSUE TITLE
All links to http://www.coolapk.com are unavailable.

### ISSUE THREAD

**Issue by Risgit** [sertwen/Mi-Mix2s-ROM#1]
All links to http://www.coolapk.com are unavailable.
Is it possible to try download links to a more accessible resource?

**Comment by Sertwen** [comment]
Sorry, I haven't confirmed the security policy of the website.
The website blocks access from non-Chinese IPs by default.
You can use a VPN with a Chinese IP to access it, or visit the OneDrive link I provided.

抱歉，我没有确认网站的安全策略。
该网站默认屏蔽了非中国的IP访问。
您可以使用具有中国IP的VPN进行访问，或者访问我提供的OneDrive链接。

**Comment by Sertwen** [comment]
I have closed this issue.
If you have other questions, please submit a new issue.

我关闭了此issues。
如果您有其他问题，欢迎提交新的issues。

**Comment by Risgit** [comment]
Can you fix the link to Microsoft Drive? The link is not available.
Thank you!
